version: "3.8"

services:
  mongodb:
    container_name: mongodatabase
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./mongodb/.env
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
